### ISSUE TITLE
The +#Armor affix doesn't seem to be working

### ISSUE THREAD

**Issue by Jateri** [josdemmers/Diablo4Companion#104] opened 2024-05-23 12:52 UTC
I can't get the overlay to mark the +#Armor affix. I checked the folder and there doesn't even seem to be a corresponding image for it, only one for total armor. Which image (if any) is the +#armor affix using?

**Comment by josdemmers** [comment] 2024-05-23 13:10
Hi @Jateri the app no longer requires any images to detect affixes. It's now able to just read the text.

The problem with +Armor is a bug some affixes have problems with. It's caused by the `Advanced tooltip information` setting ingame. As a temporarily fix you could disable that setting, or look at the debug tab and see what affix is actual detected and temporarily add that one. (ice armor)

For more info see:
https://github.com/josdemmers/Diablo4Companion/issues/98#issuecomment-2126235990

I'm planning to look into this in the weekend to try to get it working without disabling the Advanced tooltip information setting.

**Comment by josdemmers** [comment] 2024-05-25 10:19
Fixed in v3.4.4.0

**Closed by josdemmers** 2024-05-25 10:19 UTC
Labels: bug
