### ISSUE TITLE
dont show selected affix and show non-selected

### ISSUE THREAD

**Issue by visteras** [josdemmers/Diablo4Companion#61] opened 2023-10-27 09:00 UTC
hi! i got resolution 3440:1440, sdr, medium fonts. base on `1440p_SMF_en`
I dont selected any resistance in any item, and i selected intelligence for weapon, next see scrinshots...

![image](https://github.com/josdemmers/Diablo4Companion/assets/4115292/5b9dd0a6-56aa-4538-a2b9-71c419ed9e82)
in boots i see poison res but not see mana cost(i selected mana cost)
![image](https://github.com/josdemmers/Diablo4Companion/assets/4115292/5910d662-15e3-4389-8331-6d73c5fb3994)
and i dont see ball lightning and total armour(non selected only fire res):
![image](https://github.com/josdemmers/Diablo4Companion/assets/4115292/23b7636a-cebd-4247-9ed9-155ac0ecec3b)

P.S. please add auto-update for image folder when set screenshots for affix/aspect, i need restart app for set it...

**Comment by josdemmers** [comment] 2023-10-27 15:18
Your issues are related to two things.
**First one**
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/0f44135b-f574-4996-bfd6-4105c0e32b2a)
As you can see not all affixes are detected. No green/red dot visible.
This happens because `dot-affixes_1.png` was slightly changed with the season 2 update. You can find a new `dot-affixes_1.png` in the latest `1440p_SMF_en.zip` file.
Or as alternative you can change this setting to 0.07.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/26b99259-1c50-4aa4-8cde-cda9701702ae)

**Second one**
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/6a01323b-2876-4210-b10b-ff11d1bc6903)
This one is unfortunately caused by Blizzard with the season 2 update. When you reroll an affix the dot disappears. Because the app uses the dots to detect the location of the affixes it gets confused and marks the one above it.
Nothing I can do about this one. We will have to wait until Blizzard fixes this.

It is supposed to look like this:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/ec6b66dd-cf73-4d4a-a614-06ecff79a750)

> P.S. please add auto-update for image folder when set screenshots for affix/aspect, i need restart app for set it...

That is already on my todo list, I'll try to improve that this weekend.
It might be needed to toggle the overlay off for that to work, but that would be a lot quicker than restarting the app.

**Comment by josdemmers** [comment] 2023-10-27 16:12
> P.S. please add auto-update for image folder when set screenshots for affix/aspect, i need restart app for set it...

Looks easier than expected. Will do some tests tomorrow but I think you can just keep the overlay active while adding images.

**Comment by visteras** [comment] 2023-10-28 05:33
> This one is unfortunately caused by Blizzard with the season 2 update. When you reroll an affix the dot disappears. Because the app uses the dots to detect the location of the affixes it gets confused and marks the one above it.

I think we can check few point on two line:
![image](https://github.com/josdemmers/Diablo4Companion/assets/4115292/05cf1686-840d-45ea-a127-01eb520f4b67)
First line for check exist affix, second - for check (new!) affix, other color can help find line between point, plus we can check if item is ancestral and if finded only 3 default points... plus additional check if distance between default points more than X pixels if we looking situation when crafted affix got not first and not last position...

**Comment by josdemmers** [comment] 2023-10-29 15:30
> P.S. please add auto-update for image folder when set screenshots for affix/aspect, i need restart app for set it...

Fixed with the v2.2.0.0 update

**Comment by josdemmers** [comment] 2023-10-29 15:47
Thank you for the ideas. But there are too many edge cases to get it working like that. (and still be fast enough)
See image below for some examples:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/c9a9c3ff-696e-4fad-9206-eac9ec10db9c)
`[12 - 34] %` does not have to be on the first line. Can be on the second or third as well for multiline affixes. Parts can even be on different lines.

Currently the detection works like this:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/fc36b89e-a37e-4f7b-8dcc-c5445ced1278)

The dots in front of the affixes are used to create a small area. Within this area the algorithm then searches for the affix.
The reason to first specify a smaller search area is too make the detection a lot faster.
If you would search the whole tooltip you will get noticeable delays.

Let's wait for now and hope that Blizzard fixes this.

**Closed** 2023-11-13 07:43 UTC
