### ISSUE TITLE
Can't import from D4Builds

### ISSUE THREAD

**Issue by kiko9595** [josdemmers/Diablo4Companion#114] opened 2024-08-05 19:09 UTC
Hello,

I used D4 Companion for Diablo 4 Season 4 without any problems.
Tonight I wanted to import Rob's build, and nothing is displayed.
Can you help me solve the problem so that I can use D4 Companion again?

Lien : h ttps://d4builds.gg/builds/61b0ab6c-0ae1-4093-810a-17e354786ca4/?var=2
Import : 61b0ab6c-0ae1-4093-810a-17e354786ca4

![d4build 1](https://github.com/user-attachments/assets/3066019d-a9ec-4e58-b3fe-32139b679716)

![d4build 2](https://github.com/user-attachments/assets/7857fdb1-48ff-4efa-bc87-254880401bc8)

Log :
2024-08-05 20:58:24.4905|ERROR|D4Companion.Services.BuildsManagerD4Builds|LoadAvailableD4BuildsBuilds
System.Text.Json.JsonException: The JSON value could not be converted to D4Companion.Entities.D4buildsAffix. Path: $.Variants[0].Helm[0] | LineNumber: 2719 | BytePositionInLine: 22.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at D4Companion.Services.BuildsManagerD4Builds.LoadAvailableD4BuildsBuilds()
2024-08-05 20:58:24.6967|INFO|D4Companion.ViewModels.SettingsViewModel|Current system preset: 1440p_SSF_en
2024-08-05 20:58:24.8535|INFO|D4Companion.Services.ReleaseManager|Updating release info from: https://api.github.com/repos/josdemmers/diablo4Companion/releases
2024-08-05 20:58:25.0304|INFO|D4Companion.ViewModels.MainWindowViewModel|Diablo IV Companion v3.8.1.0
2024-08-05 20:58:25.0487|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:58:25.0487|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:58:35.4383|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:58:35.4383|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:58:45.4697|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:58:45.4697|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:58:55.5008|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:58:55.5008|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:05.5159|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:05.5159|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:15.5361|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:15.5361|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:24.4107|ERROR|D4Companion.Services.BuildsManagerD4Builds|LoadAvailableD4BuildsBuilds
System.Text.Json.JsonException: The JSON value could not be converted to D4Companion.Entities.D4buildsAffix. Path: $.Variants[0].Helm[0] | LineNumber: 2719 | BytePositionInLine: 22.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at D4Companion.Services.BuildsManagerD4Builds.LoadAvailableD4BuildsBuilds()
2024-08-05 20:59:25.5519|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:25.5519|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:35.5669|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:35.5669|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:45.5851|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:45.5851|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV (GeForceNOW) processes found: 0. Retry in 10 seconds.
2024-08-05 20:59:55.6042|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.

**Comment by josdemmers** [comment] 2024-08-05 20:06
Thanks for the report.

Not related to your error but:
Rob's Whirlwind Barb (S5): `61b0ab6c-0ae1-4093-810a-17e354786ca4`
Rob's Upheaval Leveling & Endgame (S5): `2898e4d5-2166-4e2c-8a09-6af6ab66ce49`

Looks like the imports are not working because the D4Builds website has changed.
I'm planning to prepare for the season 5 changes tomorrow and will work on the D4Builds changes as well.

Regarding the `System.Text.Json.JsonException` lines in your log file. Those are caused by older builds you used in season 4.
You can delete the following folders to remove those builds:

`.\Diablo4Companion\Builds\D4Builds\`
`.\Diablo4Companion\Builds\Maxroll\`
`.\Diablo4Companion\Builds\Mobalytics\`

**Comment by Nokami93** [comment] 2024-08-05 23:27
Sadly my imports are also not working.

Importing: https://d4builds.gg/builds/ebd65559-afe8-4a58-9eb4-78a1bea16d4e/?var=0
-> ebd65559-afe8-4a58-9eb4-78a1bea16d4e

After Download no Affixes, etc, are shown.

**Comment by kiko9595** [comment] 2024-08-06 07:17
Thank you very much for your response josdemmers. 
I hope you have enough time to modify everything so that everything can work again.
Thanks also for this great little program.

**Comment by josdemmers** [comment] 2024-08-06 12:39
@kiko9595 @Nokami93 
Fixed with the v3.8.2.0 release.

**Comment by kiko9595** [comment] 2024-08-06 13:16
@josdemmers 

Thank you !! It works
I bought you a coffee (paypal)

**Comment by josdemmers** [comment] 2024-08-06 13:53
You're welcome, and thanks for the coffee!
Good luck with season 5.

**Closed by josdemmers** 2024-08-06 13:53 UTC
